// <auto-generated />
using System;
using LinkNodeInfrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LinkNodeInfrastructure.Migrations
{
    [DbContext(typeof(DbLinkNodeContext))]
    [Migration("20260324181925_AddIdentityTables")]
    partial class AddIdentityTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LinkNodeDomain.Model.ActionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("actionId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.HasKey("Id")
                        .HasName("ActionTypes_pkey");

                    b.ToTable("ActionTypes");
                });

            modelBuilder.Entity("LinkNodeDomain.Model.AdminAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionId")
                        .HasColumnType("integer")
                        .HasColumnName("actionId");

                    b.Property<int>("AdminId")
                        .HasColumnType("integer")
                        .HasColumnName("adminId");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("TargetUserId")
                        .HasColumnType("integer")
                        .HasColumnName("targetUserId");

                    b.Property<int?>("TargetVacancyId")
                        .HasColumnType("integer")
                        .HasColumnName("targetVacancyId");

                    b.HasKey("Id")
                        .HasName("AdminActions_pkey");

                    b.HasIndex("ActionId");

                    b.HasIndex("AdminId");

                    b.HasIndex("TargetUserId");

                    b.HasIndex("TargetVacancyId");

                    b.ToTable("AdminActions", (string)null);
                });

            modelBuilder.Entity("LinkNodeDomain.Model.CallStatusStory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("storyId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("changedDate");

                    b.Property<int>("IntroId")
                        .HasColumnType("integer")
                        .HasColumnName("introId");

                    b.Property<int>("NewStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("newStatusId");

                    b.Property<int>("OldStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("oldStatusId");

                    b.HasKey("Id")
                        .HasName("CallStatusStories_pkey");

                    b.HasIndex("IntroId");

                    b.HasIndex("NewStatusId");

                    b.HasIndex("OldStatusId");

                    b.ToTable("CallStatusStories");
                });

            modelBuilder.Entity("LinkNodeDomain.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("categoryId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.HasKey("Id")
                        .HasName("Categories_pkey");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("LinkNodeDomain.Model.Client", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("clientId");

                    b.Property<decimal?>("AvgHourlyRatePaid")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("avgHourlyRatePaid");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text")
                        .HasColumnName("companyName");

                    b.Property<int?>("HireRate")
                        .HasColumnType("integer")
                        .HasColumnName("hireRate");

                    b.HasKey("Id")
                        .HasName("Clients_pkey");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("LinkNodeDomain.Model.EmploymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("empTypeId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EmpType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("empType");

                    b.HasKey("Id")
                        .HasName("EmploymentType_pkey");

                    b.ToTable("EmploymentTypes");
                });

            modelBuilder.Entity("LinkNodeDomain.Model.Freelancer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("freelancerId");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("categoryId");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("EmpTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("empTypeId");

                    b.Property<decimal>("HourlyRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("hourlyRate");

                    b.HasKey("Id")
                        .HasName("Freelancers_pkey");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EmpTypeId");

                    b.ToTable("Freelancers");
                });

            modelBuilder.Entity("LinkNodeDomain.Model.Interview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("introId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdDate");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("dateTime");

                    b.Property<int>("InterviewRound")
                        .HasColumnType("integer")
                        .HasColumnName("interviewRound");

                    b.Property<int>("IntroStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("introStatusId");

                    b.Property<int>("PropId")
                        .HasColumnType("integer")
                        .HasColumnName("propId");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.HasKey("Id")
                        .HasName("Interview_pkey");

                    b.HasIndex("IntroStatusId");

                    b.HasIndex("PropId");

                    b.ToTable("Interviews");
                });

            modelBuilder.Entity("LinkNodeDomain.Model.IntroStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("introStatusId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("IntroStatuses_pkey");

                    b.ToTable("IntroStatuses");
                });

            modelBuilder.Entity("LinkNodeDomain.Model.Invite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("inviteId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FreelancerId")
                        .HasColumnType("integer")
                        .HasColumnName("freelancerId");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("statusId");

                    b.Property<int>("VacancyId")
                        .HasColumnType("integer")
                        .HasColumnName("vacancyId");

                    b.HasKey("Id")
                        .HasName("Invites_pkey");

                    b.HasIndex("FreelancerId");

                    b.HasIndex("StatusId");

                    b.HasIndex("VacancyId");

                    b.ToTable("Invites");
                });

            modelBuilder.Entity("LinkNodeDomain.Model.InviteStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("statusId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("InviteStatus1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("inviteStatus");

                    b.HasKey("Id")
                        .HasName("InviteStatus_pkey");

                    b.ToTable("InviteStatuses");
                });

            modelBuilder.Entity("LinkNodeDomain.Model.Proposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("propId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("FreelancerId")
                        .HasColumnType("integer")
                        .HasColumnName("freelancerId");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<int>("VacancyId")
                        .HasColumnType("integer")
                        .HasColumnName("vacancyId");

                    b.HasKey("Id")
                        .HasName("Proposals_pkey");

                    b.HasIndex("FreelancerId");

                    b.HasIndex("VacancyId");

                    b.ToTable("Proposals");
                });

            modelBuilder.Entity("LinkNodeDomain.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("userId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdDate");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isActive");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("surname");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedDate");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("UserRoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("Users_pkey");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("UserRoleId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LinkNodeDomain.Model.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("roleId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("UserRoles_pkey");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("LinkNodeDomain.Model.Vacancy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("vacancyId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("categoryId");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("clientId");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("closedDate");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("EmpTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("empTypeId");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("Vacancies_pkey");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ClientId");

                    b.HasIndex("EmpTypeId");

                    b.ToTable("Vacancies");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LinkNodeDomain.Model.AdminAction", b =>
                {
                    b.HasOne("LinkNodeDomain.Model.ActionType", "Action")
                        .WithMany("AdminActions")
                        .HasForeignKey("ActionId")
                        .IsRequired()
                        .HasConstraintName("AdminActions_actionId_fkey");

                    b.HasOne("LinkNodeDomain.Model.User", "Admin")
                        .WithMany("AdminActions")
                        .HasForeignKey("AdminId")
                        .IsRequired()
                        .HasConstraintName("AdminActions_adminId_fkey");

                    b.HasOne("LinkNodeDomain.Model.User", "TargetUser")
                        .WithMany("AdminTargetUsers")
                        .HasForeignKey("TargetUserId")
                        .HasConstraintName("AdminActions_targetUserId_fkey");

                    b.HasOne("LinkNodeDomain.Model.Vacancy", "TargetVacancy")
                        .WithMany("AdminActions")
                        .HasForeignKey("TargetVacancyId")
                        .HasConstraintName("AdminActions_targetVacancyId_fkey");

                    b.Navigation("Action");

                    b.Navigation("Admin");

                    b.Navigation("TargetUser");

                    b.Navigation("TargetVacancy");
                });

            modelBuilder.Entity("LinkNodeDomain.Model.CallStatusStory", b =>
                {
                    b.HasOne("LinkNodeDomain.Model.Interview", "Intro")
                        .WithMany("CallStatusStories")
                        .HasForeignKey("IntroId")
                        .IsRequired()
                        .HasConstraintName("CallStatusStories_introId_fkey");

                    b.HasOne("LinkNodeDomain.Model.IntroStatus", "NewStatus")
                        .WithMany("CallStatusStoryNewStatuses")
                        .HasForeignKey("NewStatusId")
                        .IsRequired()
                        .HasConstraintName("CallStatusStories_newStatusId_fkey");

                    b.HasOne("LinkNodeDomain.Model.IntroStatus", "OldStatus")
                        .WithMany("CallStatusStoryOldStatuses")
                        .HasForeignKey("OldStatusId")
                        .IsRequired()
                        .HasConstraintName("CallStatusStories_oldStatusId_fkey");

                    b.Navigation("Intro");

                    b.Navigation("NewStatus");

                    b.Navigation("OldStatus");
                });

            modelBuilder.Entity("LinkNodeDomain.Model.Client", b =>
                {
                    b.HasOne("LinkNodeDomain.Model.User", "ClientNavigation")
                        .WithOne("Client")
                        .HasForeignKey("LinkNodeDomain.Model.Client", "Id")
                        .IsRequired()
                        .HasConstraintName("Clients_userId_fkey");

                    b.Navigation("ClientNavigation");
                });

            modelBuilder.Entity("LinkNodeDomain.Model.Freelancer", b =>
                {
                    b.HasOne("LinkNodeDomain.Model.Category", "Category")
                        .WithMany("Freelancers")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("Freelancers_categoryId_fkey");

                    b.HasOne("LinkNodeDomain.Model.EmploymentType", "EmpType")
                        .WithMany("Freelancers")
                        .HasForeignKey("EmpTypeId")
                        .IsRequired()
                        .HasConstraintName("Freelancers_empTypeId_fkey");

                    b.HasOne("LinkNodeDomain.Model.User", "FreelancerNavigation")
                        .WithOne("Freelancer")
                        .HasForeignKey("LinkNodeDomain.Model.Freelancer", "Id")
                        .IsRequired()
                        .HasConstraintName("Freelancers_userId_fkey");

                    b.Navigation("Category");

                    b.Navigation("EmpType");

                    b.Navigation("FreelancerNavigation");
                });

            modelBuilder.Entity("LinkNodeDomain.Model.Interview", b =>
                {
                    b.HasOne("LinkNodeDomain.Model.IntroStatus", "IntroStatus")
                        .WithMany("Interviews")
                        .HasForeignKey("IntroStatusId")
                        .IsRequired()
                        .HasConstraintName("Interviews_introStatusId_fkey");

                    b.HasOne("LinkNodeDomain.Model.Proposal", "Prop")
                        .WithMany("Interviews")
                        .HasForeignKey("PropId")
                        .IsRequired()
                        .HasConstraintName("Interview_propId_fkey");

                    b.Navigation("IntroStatus");

                    b.Navigation("Prop");
                });

            modelBuilder.Entity("LinkNodeDomain.Model.Invite", b =>
                {
                    b.HasOne("LinkNodeDomain.Model.Freelancer", "Freelancer")
                        .WithMany("Invites")
                        .HasForeignKey("FreelancerId")
                        .IsRequired()
                        .HasConstraintName("Invites_freelancerId_fkey");

                    b.HasOne("LinkNodeDomain.Model.InviteStatus", "Status")
                        .WithMany("Invites")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("Invites_statusId_fkey");

                    b.HasOne("LinkNodeDomain.Model.Vacancy", "Vacancy")
                        .WithMany("Invites")
                        .HasForeignKey("VacancyId")
                        .IsRequired()
                        .HasConstraintName("Invites_vacancyId_fkey");

                    b.Navigation("Freelancer");

                    b.Navigation("Status");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("LinkNodeDomain.Model.Proposal", b =>
                {
                    b.HasOne("LinkNodeDomain.Model.Freelancer", "Freelancer")
                        .WithMany("Proposals")
                        .HasForeignKey("FreelancerId")
                        .IsRequired()
                        .HasConstraintName("Proposals_freelancerId_fkey");

                    b.HasOne("LinkNodeDomain.Model.Vacancy", "Vacancy")
                        .WithMany("Proposals")
                        .HasForeignKey("VacancyId")
                        .IsRequired()
                        .HasConstraintName("Proposals_vacancyId_fkey");

                    b.Navigation("Freelancer");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("LinkNodeDomain.Model.User", b =>
                {
                    b.HasOne("LinkNodeDomain.Model.UserRole", null)
                        .WithMany("Users")
                        .HasForeignKey("UserRoleId");
                });

            modelBuilder.Entity("LinkNodeDomain.Model.Vacancy", b =>
                {
                    b.HasOne("LinkNodeDomain.Model.Category", "Category")
                        .WithMany("Vacancies")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("Vacancies_categoryId_fkey");

                    b.HasOne("LinkNodeDomain.Model.Client", "Client")
                        .WithMany("Vacancies")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("Vacancies_clientId_fkey");

                    b.HasOne("LinkNodeDomain.Model.EmploymentType", "EmpType")
                        .WithMany("Vacancies")
                        .HasForeignKey("EmpTypeId")
                        .IsRequired()
                        .HasConstraintName("Vacancies_empTypeId_fkey");

                    b.Navigation("Category");

                    b.Navigation("Client");

                    b.Navigation("EmpType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("LinkNodeDomain.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("LinkNodeDomain.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinkNodeDomain.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("LinkNodeDomain.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LinkNodeDomain.Model.ActionType", b =>
                {
                    b.Navigation("AdminActions");
                });

            modelBuilder.Entity("LinkNodeDomain.Model.Category", b =>
                {
                    b.Navigation("Freelancers");

                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("LinkNodeDomain.Model.Client", b =>
                {
                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("LinkNodeDomain.Model.EmploymentType", b =>
                {
                    b.Navigation("Freelancers");

                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("LinkNodeDomain.Model.Freelancer", b =>
                {
                    b.Navigation("Invites");

                    b.Navigation("Proposals");
                });

            modelBuilder.Entity("LinkNodeDomain.Model.Interview", b =>
                {
                    b.Navigation("CallStatusStories");
                });

            modelBuilder.Entity("LinkNodeDomain.Model.IntroStatus", b =>
                {
                    b.Navigation("CallStatusStoryNewStatuses");

                    b.Navigation("CallStatusStoryOldStatuses");

                    b.Navigation("Interviews");
                });

            modelBuilder.Entity("LinkNodeDomain.Model.InviteStatus", b =>
                {
                    b.Navigation("Invites");
                });

            modelBuilder.Entity("LinkNodeDomain.Model.Proposal", b =>
                {
                    b.Navigation("Interviews");
                });

            modelBuilder.Entity("LinkNodeDomain.Model.User", b =>
                {
                    b.Navigation("AdminActions");

                    b.Navigation("AdminTargetUsers");

                    b.Navigation("Client");

                    b.Navigation("Freelancer");
                });

            modelBuilder.Entity("LinkNodeDomain.Model.UserRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("LinkNodeDomain.Model.Vacancy", b =>
                {
                    b.Navigation("AdminActions");

                    b.Navigation("Invites");

                    b.Navigation("Proposals");
                });
#pragma warning restore 612, 618
        }
    }
}
